version: 2

models:
  - name: dim_customers
    description: >
      Customer dimension table that contains unique cardholders.
      Includes a representative country per cardholder based on transaction records.
    columns:
      - name: cardholder_id
        description: Unique identifier for each cardholder
        tests:
          - not_null
          - unique

  - name: dim_products
    description: >
      Product dimension table that contains unique product codes.
      For each product (stock_code), one representative description is chosen based on the most recent transaction.
    columns:
      - name: stock_code
        description: Unique product code for each item
        tests:
          - not_null
          - unique
      - name: description
        description: Representative product name chosen from the latest transaction

  - name: fct_transactions
    description: >
      Fact table that contains detailed card transaction records.
      Each row represents a single item purchased in a transaction, including product, customer, and amount information.
    columns:
      - name: transaction_id
        description: Transaction identifier (InvoiceNo), may be shared across multiple items
        tests:
          - not_null
      - name: cardholder_id
        description: Reference to the customer who made the transaction
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: cardholder_id
      - name: stock_code
        description: Reference to the purchased product
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: stock_code
      - name: quantity
        description: Number of units purchased
      - name: amount
        description: Unit price of the item at time of purchase
      - name: transaction_date
        description: Timestamp when the transaction occurred
      - name: country
        description: Country where the transaction was made
