version: 2

sources:
  - name: raw
    database: retail        # PostgreSQL DB명 (docker-compose 기준)
    schema: public          # 테이블 생성한 schema (별도 안 줬다면 public)
    tables:
      - name: card_transactions
